### ISSUE TITLE
Add Orcid to list of social media fields for people

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#15]
Hi Stefan. 

We would like to add Orcid to the list of available social media options in people.yaml and then have it displayed in the events template, if available

```yaml
- name: DARIAH Campus
  slug: dariah
  title: Editor
  description:
  avatar: ../images/authors/dariah.png
  email:
  linkedin:
  twitter:
  website:
```

I don't know if we have an Orcid icon in our font file, but if we don't (it looks like "id" in a green circle), we'll probably have to create our own, or, indeed, use an image.

Let me know if this makes sense.

All best,
Toma
