### ISSUE TITLE
Font-size issues

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#24]
I made the `-- container-small` slightly narrower. I would also like to increase the font size —  only in the main column for resources, but not in headings, or TOC or the metadata etc... 

So I wanted to change

```css
body {
  font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
    Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  font-size: var(--font-size-medium);
  line-height: var(--line-height-medium);
  min-width: 32rem;
  overflow-x: hidden;
}
```

to 

```css
body {
  font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
    Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  font-size: var(--font-size-large);
  line-height: var(--line-height-large);
  min-width: 32rem;
  overflow-x: hidden;
}

```

in global.css, just to see the effect, but for some reason that didn't do anything to the font size. Can you look into why and let me know how to do it correctly.
